main: de.mark225.bluebridge.worldborders.BlueBridgeWB
name: BlueBridgeWB
version: ${gradleVersion}
authors: [ ${ contributors } ]
website: https://github.com/Mark-225/BlueBridge
api-version: 1.13
depend: [ "BlueBridgeCore" ]